raise Exception("Manual exception raised!")
